### ISSUE TITLE
rewrite scala test harnesses to java

### ISSUE THREAD

**Issue by radai-rosenblatt** [linkedin/li-apache-kafka-clients#18]
could get rid of scala completely ...

**Comment by benmccann** [comment]
+1 to getting rid of Scala. I think doing that would require splitting this repo into two. The test harnesses also depend on Scala because of the following dependencies:

    compile 'org.apache.kafka:kafka_2.10:0.10.1.1:test'
    compile 'org.apache.kafka:kafka_2.10:0.10.1.1'

We shouldn't have test code and server code in these clients, so it would make sense to create a test-utils project that has the test harnesses.

One thing I'm a little unsure of is that there are integration tests for the core code that use the test harnesses. Radai's suggestions:

>i _think_  the test harnesses are used to start up embedded ZK/kafka for unit tests
easiest would be to write equivalent classes in pure java
next easiest would be to make upstream kafka build produce a test jar artifact, make our clients have a test-scope dep. on this test jar

**Comment by radai-rosenblatt** [comment]
java test harness now exists
